//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting_of_Goods_ver_2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Entrance_2
    {
        public int ID { get; set; }
        public int Products_Registration_number { get; set; }

        [Required]
        [StringLength(100)]
        public string Retail_outlets_Addressr { get; set; }

        [Required]
        [Range(1, 100000)]
        public int Product_quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Retail_outlets Retail_outlets { get; set; }
    }
}
